### PR TITLE
Update swagger-parser to support OAS 3.0.2

### PR DESCRIPTION
**Pull request by ackintosh**
This PR closes https://github.com/arjun-g/vs-swagger-viewer/issues/48

I've tested the updated extension locally. It looks fine. 👌 

image

### CODE REVIEW

**Comment by ackintosh** [comment]
ping @arjun-g 😄

**Comment by arjun-g** [comment]
Thank you @ackintosh . Will be published along with the next version changes I am working on.

**Comment by ackintosh** [comment]
I'm looking forward to use the next version. 😌 ✨

**Comment by etherealite** [comment]
Love your work. I just wanted to mention that I was confused about support for the 3.0.X specification. The readme makes no mention of 3.0.X support so I assumed that there was none. I'm sure I'm not the first to have made such a mistake.

THANX!

**Pull request merged**
